version: '3.5'
services:
  app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile
    # # Set environment variables directly in the docker-compose file
    # environment:
    #   ENV_VARIABLE: ${ENV_VARIABLE}
    #   NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # # Set environment variables based on the .env file
    # env_file:
    #   - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./pages:/app/pages
      - ./tests:/app/tests
      - ./public:/app/public
    

