import Table from "@/src/components/table";
import axios from "axios";
import { GetServerSideProps } from "next";
import Head from "next/head";

export default function Home({ users }: any) {
  const headers = [
    { field: "id", headerName: "ID" },
    { field: "nome", headerName: "Nome", minWidth: 180, editable: true },
    {
      field: "numeroDocumento",
      headerName: "Nº Doc",
      editable: true,
    },
    {
      field: "tipoDocumento",
      headerName: "Tipo Doc",
      editable: true,
    },
    {
      field: "logradouro",
      headerName: "Logradouro",
      minWidth: 180,
      editable: true,
    },
    {
      field: "numero",
      headerName: "Número",
      editable: true,
    },
    {
      field: "bairro",
      headerName: "Bairro",
      editable: true,
    },
    {
      field: "cidade",
      headerName: "Cidade",
      editable: true,
    },
    {
      field: "uf",
      headerName: "Estado",
      editable: true,
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p>
            Get started by editing&nbsp;
            <code>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
            </a>
          </div>
        </div>

        <Table data={users} headers={headers} fieldToFocus="nome" />

        <div>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const users = await fetch("http://localhost:3000/api/users").then((res) =>
    res.json()
  );
  return { props: { users } };
};
